# @package _group_

name: "CnnTell"

optim_name: "Adam"
lr: 0.0005
weight_decay: 1e-6
verbose: ${verbose}

dpath_pretrained: ${path.pretrained}
freeze_cnn14: true
beam_size: 10

use_cutout: false
use_mixup: false
use_specaugm: false
beam_alpha: 0.0
